---
title: "Final Code"
author: "Kate Davey, Emilio Lugo, Mike Ward"
date: '2022-05-01'
output: html_document
---
#Installing Packages
```{r include=FALSE}
source("https://raw.github.com/neilhatfield/STAT461/master/rScripts/checkSetup.R")
checkSetup()
packages <- c("tidyverse", "hasseDiagram", "knitr", "kableExtra", "car", "psych", "parameters", "dplyr",  "DescTools", "emmeans", "openxlsx", "lme4", "nlme", "rstatix", "coin", "rcompanion") 
lapply(packages, library, character.only = TRUE)
options(knitr.kable.NA = "")
options(contrasts = c("contr.sum", "contr.poly"))
source("https://raw.github.com/neilhatfield/STAT461/master/rScripts/ANOVATools.R")

```

#factors
```{r}
GameData<-Data
GameData <- GameData %>%
  dplyr::mutate( 
    production = dplyr::recode_factor( 
      production, 
      "< 3 years" = "< 3 years",
      "3-5 years" = "3-5 years", 
      ">5 years" = "> 5 years", "> 5 years" = "> 5 years" 
    )
  )

GameData$genre <- as.factor(GameData$genre)
GameData$series <- as.factor(GameData$series)
GameData$exclusive <- as.factor(GameData$exclusive)
GameData$production <- as.factor(GameData$production)
GameData$post <- as.factor(GameData$post)
str(GameData)
```

#Visualizations
```{r}
ggplot( 
  data = GameData, 
  mapping = aes( 
    x = production, 
    y = copies, 
  ) 
) + 
  geom_boxplot() + 
  theme_bw() + 
  xlab("Production Time") + 
  ylab("Copies (in Millions)") + 
  theme( 
    legend.position = "right",
    text = element_text(size = 14,)
  )+
  labs(title = ("Box Plot of Game Data"))
```

#Descriptive Statistics

```{r}
GameStats <- psych::describeBy(
  x = GameData$copies, # Notice how we're getting the factorial treatments 
  group = paste(GameData$production, sep = " x "), 
  na.rm = TRUE, 
  skew = TRUE, 
  ranges = TRUE, 
  quant = c(0.25, 0.75),
  IQR = TRUE, 
  mat = TRUE, 
  digits = 4
)

GameStats %>% 
  tibble::remove_rownames() %>%
  tibble::column_to_rownames(
    var = "group1" 
  ) %>% 
  dplyr::select(
    n, min, Q0.25, median, Q0.75, max, mad, mean, sd, skew, kurtosis 
  ) %>% 
  knitr::kable(
    caption = "Summary Statistics for Game Data",
    digits = 3,
    format.args = list(big.mark = ","),
    align = rep('c', 11),
    col.names = c("n", "Min", "Q1", "Median", "Q3", "Max", "MAD", "SAM", "SASD", "Sample Skew","Sample Ex. Kurtosis"),
    booktabs = TRUE 
  ) %>% 
  kableExtra::kable_styling(
    font_size = 12,
    latex_options = c("HOLD_position", "scale_down") 
  )
```
# Base Interaction Plot
```{r}
interaction.plot(
  x.factor = GameData$production, # First Factor 
  trace.factor = GameData$post, # Second Factor
  response = GameData$copies, # Response fun = mean, 
  type = "b", # Both points and lines 
  col = c("black","red","blue"), # Set colors for trace 
  pch = c(19, 17, 15), # Set symbols for trace 
  fixed = TRUE, legend = TRUE, 
  xlab = "Production Time",
  ylab = "Copies Sold (in Millions)",
  main = "Interaction Plot of Game Data",
  trace.label = "Post Production",
)
```

#Create Model
```{r}
GameModel <- aov(
  formula = copies ~ production+post + production:post,
  data = GameData 
)
GameModel2 <- aov(
  formula = log10(copies) ~ production+post + production:post,
  data = GameData 
)
GameModel3 <- aov(
  formula = log(copies) ~ production+post + production:post,
  data = GameData 
)
GameModel4 <- aov(
  formula = sqrt(copies) ~ production+post + production:post,
  data = GameData 
)
```

# Assess Assumptions
```{r}
#original model
car::qqPlot( 
  x = residuals(GameModel),
  distribution = "norm",
  envelope = 0.90, 
  id = FALSE, 
  pch = 20, 
  ylab = "Residuals (copies sold in millions)",
  main = "Q-Q Plot for Original Game Model"
  )
```

```{r}
#sqr rt model
car::qqPlot( 
  x = residuals(GameModel4),
  distribution = "norm",
  envelope = 0.90, 
  id = FALSE, 
  pch = 20, 
  ylab = "Residuals (copies sold in millions)",
  main = "Q-Q Plot for Square Root of Game Model"
)
```

```{r}
#natural log model
car::qqPlot( 
  x = residuals(GameModel3),
  distribution = "norm",
  envelope = 0.90, 
  id = FALSE, 
  pch = 20, 
  ylab = "Residuals (copies sold in millions)",
   main = "Q-Q Plot for natural Log of Game Model"
)
```

#gaussian
```{r}
#log10 model
car::qqPlot( 
  x = residuals(GameModel2),
  distribution = "norm",
  envelope = 0.90, 
  id = FALSE, 
  pch = 20, 
  ylab = "Residuals (copies sold in millions)",
   main = "Q-Q Plot for Log10 of Game Model"
)
```

#homoscedasticity
```{r}
ggplot( 
  data = data.frame( 
    residuals = residuals(GameModel2), 
    fitted = fitted.values(GameModel2) 
  ), 
  mapping = aes(x = fitted, y = residuals) 
) + 
  geom_point(size = 2) + 
  geom_hline(
    yintercept = 0, 
    linetype = "dashed",
    color = "grey50" 
  ) + 
  geom_smooth( 
    formula = y ~ x,
    method = stats::loess, 
    method.args = list(degree = 1), 
    se = FALSE, 
    size = 0.5 
  ) + 
  theme_bw() + 
  xlab("Fitted values (copies sold in millions)") + 
  ylab("Residuals (copies sold in millions)") + 
  labs(title = "Strip Plot of Game Model")
```

# Omnibus test
```{r}
# Omnibus Test/Modern ANOVA Table 

parameters::model_parameters( 
  model = GameModel,
  omega_squared = "partial", # Notice the use of partial
  eta_squared = "partial", 
  epsilon_squared = "partial", 
  type = 1, # Use 1, 2, or 3 for the Type of SSQs you want 
  drop = "(Intercept)", # Drop an unneeded row for ANOVA
  verbose = FALSE # Makes the function "quiet" 
) %>% 
  dplyr::mutate(
    p = ifelse( 
      test = is.na(p),
      yes = NA, 
      no = pvalRound(p) 
    ) 
  ) %>%
  knitr::kable(
    digits = 4, 
    col.names = c("Source", "SS", "df", "MS", "F", "p-value", "Partial Omega Sq.", "Partial Eta Sq.", "Partial Epsilon Sq."),
    caption = "ANOVA Table for Game Data", 
    align = c('l',rep('c',8)),
    booktab = TRUE 
) %>% 
  kableExtra::kable_styling( 
    bootstrap_options = c("striped", "condensed"),
    font_size = 12, 
    latex_options = c("scale_down", "HOLD_position") 
  )
```
```{r}
# Omnibus Test/Modern ANOVA Table 

parameters::model_parameters( 
  model = GameModel2,
  omega_squared = "partial", # Notice the use of partial
  eta_squared = "partial", 
  epsilon_squared = "partial", 
  type = 1, # Use 1, 2, or 3 for the Type of SSQs you want 
  drop = "(Intercept)", # Drop an unneeded row for ANOVA
  verbose = FALSE # Makes the function "quiet" 
) %>% 
  dplyr::mutate(
    p = ifelse( 
      test = is.na(p),
      yes = NA, 
      no = pvalRound(p) 
    ) 
  ) %>%
  knitr::kable(
    digits = 4, 
    col.names = c("Source", "SS", "df", "MS", "F", "p-value", "Partial Omega Sq.", "Partial Eta Sq.", "Partial Epsilon Sq."),
    caption = "ANOVA Table for Game Data", 
    align = c('l',rep('c',8)),
    booktab = TRUE 
) %>% 
  kableExtra::kable_styling( 
    bootstrap_options = c("striped", "condensed"),
    font_size = 12, 
    latex_options = c("scale_down", "HOLD_position") 
  )
```
# parametric shortcut
```{r}
# Anova example with Resin Lifetime 

anova(GameModel)

```
# Create professional looking, modern ANOVA table for Song Knowledge

```{r}
parameters::model_parameters(
  model = GameModel, 
  omega_squared = "raw", 
  eta_squared = "raw", 
  epsilon_squared = "raw" 
) %>% 
  knitr::kable( 
  digits = 4, 
  col.names = c(
    "Source", "SS", "df", "MS", "F", "p-value", 
    "Omega Sq.", "Eta Sq.", "Epslion Sq."), 
  caption = "ANOVA Table for Song Knowledge Study", 
  booktabs = TRUE, 
  align = c("l", rep("c", 8)) 
  ) %>% 
  kableExtra::kable_styling( 
    font_size = 10, latex_options = c("HOLD_position") 
  )
```
# Point Estimate
```{r}
pointEst <- dummy.coef(GameModel)
```
```{R}
dummy.coef(GameModel)
```
```{r}
pointEst <- dummy.coef(GameModel) 
pointEst <- unlist(pointEst) 
names(pointEst) <- c(
  "Grand Mean", 
  levels(GameData$post),
  levels(GameData$production),
  outer(
    levels(GameData$post),
    levels(GameData$production),
    FUN = paste,
    sep = " x "
  )
)

data.frame("Estimate" = pointEst) %>%
  knitr::kable( 
  digits = 2, 
  caption = "Point Estimates from the Game Data", 
  booktabs = TRUE, align = "c" 
  ) %>%
  kableExtra::kable_styling(
    font_size = 12,
    latex_options = c("HOLD_position") 
  )
```
## Kable Code for Tukey HSD

```{r}
dtPH <- DescTools::PostHocTest(
  x = GameModel, # Your aov/lm object
  method = "newmankeuls", # Your chosen method
  conf.level = 0.9 # 1 -- Your Overall Type I Error Rate 
)
```
## Kable Code for DescTools

```{r}
knitr::kable(
  x = dtPH$production, # Notice the use of the factor name
  digits = 3,
  caption = paste( # Creates a nice title; copy at will
  "Post Hoc",
  attr(dtPH, "method"),
  "Comparisons" ),
  col.names = c("Difference", "Lower Bound", "Upper Bound",         "Adj. p-Value"), 
  align = 'lcccc', booktabs = TRUE, 
) %>% 
  kableExtra::kable_styling( 
    bootstrap_options = c("condensed", "boardered"), 
    font_size = 12, 
    latex_options = "HOLD_position"
  )
```
